# online/config/runtime.yaml

sampling_rate: 256       
window_size: 1.0           
step_size: 0.25            

bandpass:
  low: 1                   
  high: 45                 

model_path: "model/va_regressor.onnx"  

websocket:
  host: "0.0.0.0"
  port: 8765

mqtt:
  broker: ""
  port: 1883
  topic: "eeg/va"

log_level: "INFO"
